server:
  port: 8080
  servlet:
    context-path: /security

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
    initialization-mode: always
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
